from llm import generate_response

test_cases = [
    ############################################################
    # TC 1
    ############################################################
    {
        "candidate-name": "Narendra Modi",
        "political-party": "Bharatiya Janata Party (BJP)",
        "other-party": "Indian National Congress, Bharat Rashtra Samithi (BRS)",
        "office-sought": "Prime Minister of India",
        "bio": "Narendra Damodardas Modi[a] (born 17 September 1950)[b] is an Indian politician who has served as the prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a far-right Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress.[4] Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he rose through the party hierarchy, becoming general secretary in 1998.[c] In 2001, Modi was appointed chief minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[d] and has been criticised for its management of the crisis. According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[13] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[e] While his policies as chief minister were credited for encouraging economic growth, his administration was criticised for failing to significantly improve health, poverty and education indices in the state.[f] In the 2014 Indian general election, Modi led the BJP to a parliamentary majority, the first for a party since 1984. His administration increased direct foreign investment, and reduced spending on healthcare, education, and social-welfare programmes. Modi began a high-profile sanitation campaign, and weakened or abolished environmental and labour laws. His demonetisation of banknotes in 2016 and introduction of the Goods and Services Tax in 2017 sparked controversy. Modi's administration launched the 2019 Balakot airstrike against an alleged terrorist training camp in Pakistan. The airstrike failed,[16][17] but the action had nationalist appeal.[18] Modi's party won the 2019 general election which followed.[19] In its second term, his administration revoked the special status of Jammu and Kashmir,[20][21] and introduced the Citizenship Amendment Act, prompting widespread protests, and spurring the 2020 Delhi riots in which Muslims were brutalised and killed by Hindu mobs.[22][23][24] Three controversial farm laws led to sit-ins by farmers across the country, eventually causing their formal repeal. Modi oversaw India's response to the COVID-19 pandemic, during which, according to the World Health Organization's estimates, 4.7 million Indians died.[25][26] In the 2024 general election, Modi's party lost its majority in the lower house of Parliament and formed a government leading the National Democratic Alliance coalition.[27][28] Under Modi's tenure, India has experienced democratic backsliding, or the weakening of democratic institutions, individual rights, and freedom of expression.[29][30][g] As prime minister, he has received consistently high approval ratings.[36][37][38] Modi has been described as engineering a political realignment towards right-wing politics. He remains a controversial figure domestically and internationally, over his Hindu nationalist beliefs and handling of the Gujarat riots, which have been cited as evidence of a majoritarian and exclusionary social agenda.[h]",
        "key-strengths": "Strong leadership, infrastructure development, national security focus, economic reforms, cultural heritage preservation",
        "target-demographic": "Residents of Warangal, Telangana; focus on urban middle class, youth, farmers, and small business owners",
        "primary-concerns": "Local infrastructure development, employment opportunities, agricultural support, cultural heritage preservation, education",
        "cultural-beliefs": "Respect for Telangana culture and heritage, Hindu traditions, national pride, inclusive development",
        "existing-values": "Hard work, family values, entrepreneurship, respect for tradition while embracing progress",
        "slogan": "Sabka Saath, Sabka Vikas, Sabka Vishwas - Prosperous Warangal, Vibrant Telangana",
        "main-message": "Transforming Warangal into a center of heritage tourism and modern development while preserving its cultural identity",
        "tone": "Empowering, confident, respectful of local traditions",
        "cultural-context": "References to Kakatiya dynasty, Warangal Fort, local festivals, and Telangana movement",
        "formality": "Formal with approachable elements that connect with local residents",
        "speech-length": "Medium (10-15 minutes)",
        "speech-type": "Local campaign rally speech",
        "primary-objective": "Build support for BJP in Warangal region by connecting national vision to local development",
        "secondary-objective": "Address specific concerns of Warangal residents and outline targeted development plans",
        "age-range": "All adult voters with emphasis on youth and middle-aged residents",
        "education-level": "Mixed - accessible to all education levels from rural farmers to urban professionals",
        "caste-community": "Inclusive appeal to all communities with sensitivity to local social dynamics",
        "religious-affiliation": "Respectful of Hindu traditions while acknowledging religious diversity in the region",
        "political-climate": "Competitive region with strong presence of regional parties (BRS) and Congress",
        "recent-events": "Infrastructure projects in Telangana, textile industry initiatives, tourism development efforts",
        "geographic-location": "Warangal, Telangana",
        "key-messages": "Heritage tourism development, educational opportunities, textile industry revival, agricultural support, infrastructure improvement",
        "data-upload": "",
        "story-elements": "References to Warangal's glorious history under Kakatiya dynasty, transformation stories of similar cities, personal connections to the region",
        "call-to-action": "Vote for BJP to make Warangal a model city combining heritage and development",
        "cta-instructions": "Encourage voters to support BJP candidates in upcoming elections and become ambassadors for change in their communities",
        "speech-tone": "Empowering, optimistic, respectful, visionary",
        "language-dialect": "English with occasional Telugu phrases to connect with local audience",
        "rhetorical-devices": "Historical parallels between Kakatiya glory and future potential, metaphors related to weaving (connecting to local textile industry), rhetorical questions about region's aspirations",
        "speech-preview": "",
        "export-options": "text",
        "policy-points": "Heritage tourism circuit development, textile industry modernization, educational institutions expansion, agricultural support schemes, infrastructure connectivity projects",
        "retrieved_info": "",
        "page": "page3"
    },
    ############################################################
    # TC 2
    ############################################################
    {
        "candidate-name": "Rahul Gandhi",
        "political-party": "Indian National Congress (INC)",
        "other-party": "Bharatiya Janata Party (BJP), Bharat Rashtra Samithi (BRS)",
        "office-sought": "Member of Parliament",
        "bio": "Rahul Rajiv Gandhi (Hindi pronunciation: [ˈraːɦʊl raːdʒiːʋ ˈɡaːndɦiː] i; born 19 June 1970) is an Indian politician. A member of the Indian National Congress (INC), he is currently serving as the 12th leader of the Opposition in Lok Sabha and as the member of the Lok Sabha for Rae Bareli, Uttar Pradesh, since June 2024.[c][d] He previously represented the constituency of Wayanad, Kerala, from 2019 to 2024, and Amethi, Uttar Pradesh, from 2004 to 2019. Gandhi served as the party president of the Indian National Congress from December 2017 to July 2019. A member of the Nehru–Gandhi political family, he spent his early years between Delhi and Dehradun, remaining largely outside the public sphere during his childhood and early youth. He received primary education in New Delhi and then attended The Doon School. However, due to security concerns, he was later home-schooled. Gandhi commenced his undergraduate degree at St. Stephen's College before moving to Harvard University. Following his father's assassination and subsequent security concerns, he moved to Rollins College in Florida, completing his degree in 1994. After earning a M.Phil. from Cambridge, Gandhi initiated his professional career with the Monitor Group, a management consulting firm in London. Soon thereafter, he returned to India and founded Backops Services Private Ltd, a technology outsourcing firm based in Mumbai. He ventured into politics in the 2000s, leading the Indian Youth Congress and National Students Union of India, while also being a trustee of the Rajiv Gandhi Foundation and Rajiv Gandhi Charitable Trust. Gandhi led the Congress party during the 2014 and 2019 general elections, where the party experienced significant defeats, securing 44 and 52 seats, respectively. Ahead of the 2024 Indian general elections, Gandhi spearheaded the Bharat Jodo Yatra and the Bharat Jodo Nyay Yatra, contributing to the INC winning 99 seats and regaining the status of Official Opposition for the first time in a decade. Gandhi won the Rae Bareli Lok Sabha constituency in the 2024 elections and was nominated to serve as Leader of the Opposition.",
        "key-strengths": "Grassroots connection, advocacy for marginalized communities, focus on social welfare, youth engagement, progressive vision",
        "target-demographic": "Residents of Warangal, Telangana; focus on farmers, laborers, minorities, youth, women, and rural communities",
        "primary-concerns": "Social inequality, farmers' rights, unemployment, healthcare access, education, tribal welfare",
        "cultural-beliefs": "Secular values, inclusive development, constitutional principles, economic justice, cultural diversity",
        "existing-values": "Equality, social justice, democratic principles, empowerment of marginalized communities",
        "slogan": "Nyay For All - Building a Just and Inclusive Warangal",
        "main-message": "Creating a Warangal where every citizen has equal opportunities, social protection, and a voice in their future",
        "tone": "Empowering, compassionate, inclusive, progressive",
        "cultural-context": "References to Telangana movement, local agricultural traditions, tribal heritage, and historical struggles for justice",
        "formality": "Conversational yet respectful, accessible to common citizens",
        "speech-length": "Medium (10-15 minutes)",
        "speech-type": "Community engagement rally",
        "primary-objective": "Connect with Warangal residents through commitment to social welfare and community development",
        "secondary-objective": "Contrast INC's inclusive vision with other parties' approaches to development",
        "age-range": "All adult voters with emphasis on youth and working-age population",
        "education-level": "Accessible to all education levels, with special focus on addressing concerns of less privileged",
        "caste-community": "Inclusive message with special attention to SC/ST communities, minorities, and other marginalized groups in Warangal",
        "religious-affiliation": "Secular approach emphasizing unity in diversity",
        "political-climate": "Competitive region with strong presence of regional parties and growing BJP influence",
        "recent-events": "Farmer protests, healthcare challenges, education accessibility issues, tribal rights movements",
        "geographic-location": "Warangal, Telangana",
        "key-messages": "Social welfare programs, farmers' rights, employment generation, healthcare reform, educational opportunities, tribal development",
        "data-upload": "",
        "story-elements": "Personal interactions with Warangal residents, stories of local community heroes, examples of successful social welfare initiatives",
        "call-to-action": "Join hands with Congress to build a more equitable and just Warangal for all",
        "cta-instructions": "Encourage community engagement, participate in local welfare programs, support Congress candidates who will prioritize social justice",
        "speech-tone": "Empowering, compassionate, determined, hopeful",
        "language-dialect": "English with occasional Telugu phrases to connect with local audience",
        "rhetorical-devices": "Anecdotes about community struggles and triumphs, contrast between current challenges and future possibilities, appeals to shared values of justice and equality",
        "speech-preview": "",
        "export-options": "text",
        "policy-points": "Universal basic income program, farm loan waivers, healthcare access expansion, educational scholarships, tribal rights protection, women's empowerment initiatives",
        "retrieved_info": "",
        "page": "page3"
    },
    ############################################################
    # TC 3
    ############################################################
    {
        "candidate-name": "Narendra Modi",
        "political-party": "Bharatiya Janata Party (BJP)",
        "other-party": "Bharat Rashtra Samithi (BRS), Indian National Congress (INC)",
        "office-sought": "Prime Minister of India",
        "bio": "Narendra Damodardas Modi[a] (born 17 September 1950)[b] is an Indian politician who has served as the prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a far-right Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress.[4] Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he rose through the party hierarchy, becoming general secretary in 1998.[c] In 2001, Modi was appointed chief minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[d] and has been criticised for its management of the crisis. According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[13] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[e] While his policies as chief minister were credited for encouraging economic growth, his administration was criticised for failing to significantly improve health, poverty and education indices in the state.[f] In the 2014 Indian general election, Modi led the BJP to a parliamentary majority, the first for a party since 1984. His administration increased direct foreign investment, and reduced spending on healthcare, education, and social-welfare programmes. Modi began a high-profile sanitation campaign, and weakened or abolished environmental and labour laws. His demonetisation of banknotes in 2016 and introduction of the Goods and Services Tax in 2017 sparked controversy. Modi's administration launched the 2019 Balakot airstrike against an alleged terrorist training camp in Pakistan. The airstrike failed,[16][17] but the action had nationalist appeal.[18] Modi's party won the 2019 general election which followed.[19] In its second term, his administration revoked the special status of Jammu and Kashmir,[20][21] and introduced the Citizenship Amendment Act, prompting widespread protests, and spurring the 2020 Delhi riots in which Muslims were brutalised and killed by Hindu mobs.[22][23][24] Three controversial farm laws led to sit-ins by farmers across the country, eventually causing their formal repeal. Modi oversaw India's response to the COVID-19 pandemic, during which, according to the World Health Organization's estimates, 4.7 million Indians died.[25][26] In the 2024 general election, Modi's party lost its majority in the lower house of Parliament and formed a government leading the National Democratic Alliance coalition.[27][28] Under Modi's tenure, India has experienced democratic backsliding, or the weakening of democratic institutions, individual rights, and freedom of expression.[29][30][g] As prime minister, he has received consistently high approval ratings.[36][37][38] Modi has been described as engineering a political realignment towards right-wing politics. He remains a controversial figure domestically and internationally, over his Hindu nationalist beliefs and handling of the Gujarat riots, which have been cited as evidence of a majoritarian and exclusionary social agenda.[h]",
        "key-strengths": "Strong leadership, nationalist vision, development track record, oratorical skills, international recognition",
        "target-demographic": "Warangal, Telangana voters across all sections with focus on youth, farmers, women, and middle class",
        "primary-concerns": "Agricultural development, irrigation projects, employment opportunities, infrastructure development, cultural heritage preservation",
        "cultural-beliefs": "Hindu nationalism, cultural pride, respect for traditional values while embracing modernization",
        "existing-values": "Self-reliance (Atmanirbhar Bharat), development for all (Sabka Saath, Sabka Vikas), national unity and pride",
        "slogan": "Viksit Bharat, Viksit Telangana",
        "main-message": "BJP will transform Telangana through development while preserving its rich cultural heritage and addressing local issues",
        "tone": "Inspirational, emotional, assertive, hopeful",
        "cultural-context": "Warangal's historical significance as ancient capital of Kakatiya dynasty, rich Telugu culture, agricultural region known for paddy cultivation",
        "formality": "Semi-formal with local cultural references",
        "speech-length": "Medium (10-15 minutes)",
        "speech-type": "Campaign rally speech",
        "primary-objective": "Increase BJP's presence and support in Telangana",
        "secondary-objective": "Address local concerns and present clear vision for regional development",
        "age-range": "All voting age groups",
        "education-level": "Mixed - rural and urban population with varying education levels",
        "caste-community": "Diverse communities including SC/ST, OBC, and forward castes",
        "religious-affiliation": "Primarily Hindu with significant Muslim and Christian minorities",
        "political-climate": "Competitive three-way contest between BJP, BRS, and Congress in Telangana",
        "recent-events": "Irrigation project delays in Telangana, farmer protests over minimum support prices, BJP's recent growth in the state, opening of Ramappa Temple as UNESCO World Heritage site",
        "geographic-location": "Warangal, Telangana - historical city with agricultural significance",
        "key-messages": "BJP's commitment to Telangana's development, addressing agricultural concerns, preserving cultural heritage, creating employment opportunities",
        "data-upload": "",
        "story-elements": "Reference to Kakatiya dynasty's glory, personal connection to visiting Warangal Fort, examples of successful BJP initiatives in other states",
        "call-to-action": "Vote for BJP to bring transformative development to Telangana",
        "cta-instructions": "Encourage supporters to spread the message, register new voters, and volunteer for campaign activities",
        "speech-tone": "Emotional, inspirational with local cultural connectivity",
        "language-dialect": "Hindi with some Telugu phrases and references",
        "rhetorical-devices": "Repetition, metaphors relating to Telangana's cultural symbols, rhetorical questions, personal stories",
        "speech-preview": "",
        "export-options": "text",
        "policy-points": "Agricultural reforms, irrigation project completion, heritage tourism development, skill development initiatives, infrastructure projects",
        "retrieved_info": "",
        "page": "page3"
    },
    ############################################################
    # TC 4
    ############################################################
    {
        "candidate-name": "Arvind Kejriwal",
        "political-party": "Aam Aadmi Party (AAP)",
        "other-party": "Bharat Rashtra Samithi (BRS), Bharatiya Janata Party (BJP), Indian National Congress (INC)",
        "office-sought": "Expanding AAP's national presence",
        "bio": "Arvind Kejriwal (Hindi pronunciation: [əɾʋin̪d̪ ked͡ʒɾiːʋaːl]; born 16 August 1968) is an Indian politician, activist and former bureaucrat, who served as the 7th Chief Minister of Delhi. He was the chief minister from 2013 to 2014 and from 2015 to 2024. He is also the national convener of the Aam Aadmi Party (AAP) since 2012. He represented the New Delhi constituency in the Delhi Legislative Assembly from 2015 to 2025, and previously from 2013 to 2014.\n\nIn 2006, Kejriwal was awarded the Ramon Magsaysay Award for his involvement in the Parivartan movement using right to information legislation in a campaign against government corruption. The same year, after resigning from government service, he founded the Public Cause Research Foundation to campaign for transparent governance. Before entering politics, Kejriwal had worked in the Indian Revenue Service. Prior to that, he was a mechanical engineer from IIT Kharagpur.\n\nIn 2012, he launched the AAP. In 2013, he assumed office as the Chief Minister of Delhi and resigned 49 days later over his inability to mobilise support for his proposed anti-corruption legislation. In the 2015 Delhi Legislative Assembly elections, the AAP registered an unprecedented majority. In subsequent 2020 elections, AAP re-emerged victorious and retained power in Delhi, following which, Kejriwal was sworn in as the Chief Minister of Delhi for the third time in a row. Outside Delhi, his party registered another major victory in the 2022 Punjab Legislative Assembly election.\n\nHe was arrested on 21 March 2024 by the Enforcement Directorate on allegations of a liquor scam against the Aam Aadmi Party led Delhi Government. He became the first ever sitting chief minister in India to be arrested. His other party leaders, Satyendra Jain, Sanjay Singh and Manish Sisodia have also spent months to years in jail without bail, trial or conviction. The opposition alliance called the arrest weeks before the 2024 Indian general election, a case of fabrication and 'match-fixing' by the BJP. Amnesty International said that financial and terrorism laws have been weaponised to go after political opponents. On 10 May, the Supreme Court ordered Kejriwal's release on interim bail until 1 June 2024, on account of campaigning for the election. Kejriwal surrendered at Tihar Jail after the expiry of his bail period on 2 June 2024. On 13 September 2024, he was granted bail by Supreme Court with certain conditions, the case still continues. On 17 September 2024, he resigned as Delhi Chief Minister saying he will only become CM again if he receives a public mandate.\n\nHis party was defeated in the 2025 Delhi Legislative Assembly election, losing his seat to Parvesh Verma by a margin of over 4,000 votes from the New Delhi Assembly constituency.",
        "key-strengths": "Anti-corruption crusader, administrative reforms, education and healthcare model in Delhi, common man appeal, urban governance expertise",
        "target-demographic": "Middle class, youth, government employees, teachers, healthcare workers, urban and semi-urban voters of Warangal",
        "primary-concerns": "Education quality, healthcare access, corruption-free governance, water management, electricity prices, urban development",
        "cultural-beliefs": "Democratic participation, civic responsibility, transparency in governance, equality across religious and caste lines",
        "existing-values": "Honesty, transparency, citizen-centric governance, social welfare, innovation in public service delivery",
        "slogan": "Badlega Telangana, Badlega Bharat",
        "main-message": "AAP's successful Delhi model of governance focusing on education, healthcare, and corruption-free administration can transform Telangana",
        "tone": "Assertive, straightforward, historically informed, solution-oriented",
        "cultural-context": "Warangal's significance as former capital of Kakatiya dynasty, historical center of Telugu resistance movements, agricultural heartland with emerging urban challenges",
        "formality": "Conversational with historical parallels",
        "speech-length": "Medium (12-15 minutes)",
        "speech-type": "Political rally speech with educational focus",
        "primary-objective": "Establish AAP as a viable alternative in Telangana politics",
        "secondary-objective": "Connect historical democratic traditions of the region to AAP's governance philosophy",
        "age-range": "18-65, with emphasis on young voters and working professionals",
        "education-level": "Mixed - urban educated population and rural agricultural communities",
        "caste-community": "Appeal across castes with emphasis on historically marginalized communities",
        "religious-affiliation": "Secular approach addressing all religious communities",
        "political-climate": "Growing disillusionment with established regional parties, seeking new political alternatives",
        "recent-events": "Water scarcity issues in Warangal, delays in promised educational institutions, controversies over Kaleshwaram Lift Irrigation Project costs, AAP's education model gaining national attention, Delhi government's Mohalla Clinics success",
        "geographic-location": "Warangal, Telangana - historic city with mix of urban and rural populations",
        "key-messages": "Education revolution similar to Delhi, mohalla clinics for healthcare access, corruption-free administration, water management solutions, employment opportunities through governance reforms",
        "data-upload": "",
        "story-elements": "Historical parallels between Kakatiyas' water management and AAP's governance innovations, personal stories of Delhi's education transformation, connecting anti-corruption movement to Telangana's freedom fighters",
        "call-to-action": "Join the new politics of honesty and development inspired by our shared historical values",
        "cta-instructions": "Form local mohalla committees, support education initiatives, report corruption, volunteer for voter awareness",
        "speech-tone": "Educational, historically rich, emotionally resonant, solution-focused",
        "language-dialect": "Hindi with Telugu phrases and historical references",
        "rhetorical-devices": "Historical parallels, rhetorical questions connecting past governance to present challenges, alliteration, metaphors based on Warangal's monuments",
        "speech-preview": "",
        "export-options": "text",
        "policy-points": "Education reforms with school infrastructure upgrades, healthcare access through neighborhood clinics, anti-corruption mechanisms, water conservation projects, electricity subsidies, urban planning improvements",
        "retrieved_info": "",
        "page": "page3"
    },
    ############################################################
    # TC 5
    ############################################################
    {
        "candidate-name": "Amit Shah",
        "political-party": "Bharatiya Janata Party (BJP)",
        "other-party": "Bharat Rashtra Samithi (BRS), Indian National Congress (INC)",
        "office-sought": "Supporting BJP candidates in Telangana",
        "bio": "Amitbhai Anilchandra Shah (born 22 October 1964) is an Indian politician who is currently serving as the 32nd Minister of Home Affairs since May 2019 and the 1st Minister of Co-operation since July 2021. He is also the member of parliament (MP) for Gandhinagar. He served as the 10th president of the Bharatiya Janata Party (BJP) from 2014 to 2020. He has also served as chairman of the National Democratic Alliance (NDA) since 2014. He had been elected as a member of the upper house of parliament, Rajya Sabha, from Gujarat from 2017 to 2019.\n\nShah is a chief strategist of the BJP and close aide to Narendra Modi. He was also the member of the Gujarat Legislative Assembly from Naranpura Assembly constituency from 2012 to 2017 and Sarkhej from 1997 to 2012 and the minister of State for Home, Law and Justice, Prison, Border Security, Civil Defence, Excise, Home Guards, Transport, Prohibition, Gram Rakshak Dal, Police Housing, Legislative and Parliamentary Affairs, government of Gujarat in the Modi ministry from 2002 to 2012. During his college days, Shah was a member of the Akhil Bharatiya Vidyarthi Parishad (ABVP), the student wing of the Rashtriya Swayamsevak Sangh (RSS). At the age of 18, he secured a position in the ABVP and joined the BJP in 1987.\n\nShah was the BJP's in-charge for India's largest and politically most crucial state, Uttar Pradesh, during the 2014 Lok Sabha elections. The BJP-led NDA won 73 out of 80 seats. As a result, Shah rose to national prominence and was appointed as the party's national president in July 2014. He has played an organising and membership-promotional role in the elections of many states since 2014. In his initial two years, the BJP achieved success in legislative assembly elections in Maharashtra, Haryana, Jammu and Kashmir, Jharkhand and Assam but lost ground in Delhi and the large eastern state of Bihar in 2015.\n\nIn 2017, he was partly credited with the party victories in Uttar Pradesh, Uttarakhand, Gujarat and Manipur, but the Akali-BJP alliance lost power in the larger Punjab election. In 2018, the party lost power in the states of Chhattisgarh, Rajasthan and Madhya Pradesh. A year later, the BJP won 303 seats to get a majority in the 2019 Indian general election under Shah's leadership.",
        "key-strengths": "Strategic vision, organizational skills, administrative experience, direct communication style, national security focus",
        "target-demographic": "All voters in Warangal, Telangana with focus on various communities including farmers, youth, women, and middle class",
        "primary-concerns": "Regional development, agricultural support, employment opportunities, security issues, infrastructure development",
        "cultural-beliefs": "National unity, cultural heritage preservation, inclusive development",
        "existing-values": "Strong leadership, development-focused governance, national security, cultural pride",
        "slogan": "Sashakt Bharat, Samriddh Telangana (Strong India, Prosperous Telangana)",
        "main-message": "BJP's vision for inclusive development and good governance in Telangana",
        "tone": "Factual, confident, respectful, solution-oriented",
        "cultural-context": "Warangal's historical significance, agricultural importance, and cultural heritage",
        "formality": "Formal with respectful references to local customs and traditions",
        "speech-length": "Medium (10-15 minutes)",
        "speech-type": "Political rally speech",
        "primary-objective": "Present BJP's vision and policies for Telangana's development",
        "secondary-objective": "Build trust across diverse communities in the region",
        "age-range": "All voting age groups",
        "education-level": "Accessible to all education levels",
        "caste-community": "Inclusive approach to all communities",
        "religious-affiliation": "Respectful of all religious communities",
        "political-climate": "Competitive political environment with multiple parties contesting",
        "recent-events": "Central government's infrastructure investments in Telangana, development of textile park near Warangal, agricultural policy reforms, increased security measures, heritage conservation efforts at Warangal Fort",
        "geographic-location": "Warangal, Telangana - historical city with significant cultural heritage",
        "key-messages": "Development-focused governance, agricultural support, infrastructure development, education and skill development, preserving cultural heritage",
        "data-upload": "",
        "story-elements": "References to Warangal's history, examples of successful development projects, comparisons with other BJP-governed states",
        "call-to-action": "Support BJP for development-focused governance in Telangana",
        "cta-instructions": "Engage with local BJP representatives, share policy benefits with communities, participate in upcoming elections",
        "speech-tone": "Balanced, factual, respectful of all communities",
        "language-dialect": "Hindi with some Telugu phrases, avoiding regional stereotypes",
        "rhetorical-devices": "Evidence-based argumentation, comparative examples, policy explanations",
        "speech-preview": "",
        "export-options": "text",
        "policy-points": "Infrastructure development, agricultural support mechanisms, education and skill development initiatives, heritage conservation, security enhancements",
        "retrieved_info": "",
        "page": "page3"
    },
    ############################################################
    # TC 6
    ############################################################
    {
        "candidate-name": "Rahul Gandhi",
        "political-party": "Indian National Congress (INC)",
        "other-party": "Bharat Rashtra Samithi (BRS), Bharatiya Janata Party (BJP)",
        "office-sought": "Supporting Congress candidates in Telangana",
        "bio": "Rahul Rajiv Gandhi (Hindi pronunciation: [ˈraːɦʊl raːdʒiːʋ ˈɡaːndɦiː] i; born 19 June 1970) is an Indian politician. A member of the Indian National Congress (INC), he is currently serving as the 12th leader of the Opposition in Lok Sabha and as the member of the Lok Sabha for Rae Bareli, Uttar Pradesh, since June 2024.[c][d] He previously represented the constituency of Wayanad, Kerala, from 2019 to 2024, and Amethi, Uttar Pradesh, from 2004 to 2019. Gandhi served as the party president of the Indian National Congress from December 2017 to July 2019. A member of the Nehru–Gandhi political family, he spent his early years between Delhi and Dehradun, remaining largely outside the public sphere during his childhood and early youth. He received primary education in New Delhi and then attended The Doon School. However, due to security concerns, he was later home-schooled. Gandhi commenced his undergraduate degree at St. Stephen's College before moving to Harvard University. Following his father's assassination and subsequent security concerns, he moved to Rollins College in Florida, completing his degree in 1994. After earning an M.Phil. from Cambridge, Gandhi initiated his professional career with the Monitor Group, a management consulting firm in London. Soon thereafter, he returned to India and founded Backops Services Private Ltd, a technology outsourcing firm based in Mumbai. He ventured into politics in the 2000s, leading the Indian Youth Congress and National Students Union of India, while also being a trustee of the Rajiv Gandhi Foundation and Rajiv Gandhi Charitable Trust. Gandhi led the Congress party during the 2014 and 2019 general elections, where the party experienced significant defeats, securing 44 and 52 seats, respectively. Ahead of the 2024 Indian general elections, Gandhi spearheaded the Bharat Jodo Yatra and the Bharat Jodo Nyay Yatra, contributing to the INC winning 99 seats and regaining the status of Official Opposition for the first time in a decade. Gandhi won the Rae Bareli Lok Sabha constituency in the 2024 elections and was nominated to serve as Leader of the Opposition.",
        "key-strengths": "Legacy of Congress contribution to India's development, focus on rural issues, commitment to secular values, advocacy for farmers and marginalized communities",
        "target-demographic": "Rural and urban voters of Warangal, farmers, youth, women, marginalized communities, working class",
        "primary-concerns": "Farmer distress, unemployment, healthcare access, education quality, water management issues, preservation of Telangana culture",
        "cultural-beliefs": "Democratic values, secularism, social justice, inclusive growth",
        "existing-values": "Constitutional principles, rights of marginalized communities, federalism, economic justice",
        "slogan": "Nyay Ho Raha Hai (Justice is Happening)",
        "main-message": "Congress offers a vision of inclusive development that addresses the specific needs of Telangana's farmers, youth, and working class",
        "tone": "Direct, empathetic, solution-oriented, concise",
        "cultural-context": "Warangal's agricultural importance, historical significance in Telangana movement, textile industry heritage",
        "formality": "Semi-formal with approachable language",
        "speech-length": "Short (7-10 minutes)",
        "speech-type": "Campaign rally speech",
        "primary-objective": "Present Congress's vision for Telangana's development with emphasis on agricultural reforms and job creation",
        "secondary-objective": "Contrast Congress approach with current governance issues",
        "age-range": "All voting age groups with focus on youth and working-age population",
        "education-level": "Accessible to all education levels",
        "caste-community": "Inclusive approach addressing concerns of all communities with special focus on marginalized groups",
        "religious-affiliation": "Secular approach respecting all religions",
        "political-climate": "Competitive multi-party contest with focus on local development issues",
        "recent-events": "Farmer protests in Telangana, implementation issues with Rythu Bandhu scheme, rising unemployment among educated youth, water disputes with neighboring states, completion of Warangal textile park project delays",
        "geographic-location": "Warangal, Telangana - agricultural center with historical significance",
        "key-messages": "Support for farmers, job creation for youth, protection of Telangana's water resources, improved healthcare and education, preservation of cultural heritage",
        "data-upload": "",
        "story-elements": "Personal interactions with Warangal farmers, examples of successful Congress initiatives in other states, references to historical Congress connection with Telangana development",
        "call-to-action": "Vote for Congress to bring practical, people-centered governance to Telangana",
        "cta-instructions": "Discuss Congress policies with neighbors, share information on party's agricultural and employment initiatives",
        "speech-tone": "Conversational, direct, fact-based, concise",
        "language-dialect": "Hindi with Telugu phrases, simple vocabulary for broader reach",
        "rhetorical-devices": "Contrast and compare, direct questions, brevity, clear policy points",
        "speech-preview": "",
        "export-options": "text",
        "policy-points": "Minimum Support Price guarantees, farm loan waivers, rural healthcare initiatives, education scholarships, water conservation projects, job creation through skill development",
        "retrieved_info": "",
        "page": "page3"
    },
    ############################################################
    # TC 7
    ############################################################
    {
        "candidate-name": "Narendra Modi",
        "political-party": "Bharatiya Janata Party (BJP)",
        "other-party": "Indian National Congress (INC)",
        "office-sought": "Prime Minister of India",
        "bio": "Narendra Modi is the Prime Minister of India, known for his leadership, vision, and dedication to national development. His government has focused on modernizing education, empowering youth, and strengthening India's global standing.",
        "key-strengths": "Inspirational leadership, strong communication skills, emphasis on development, technology-driven governance, and youth empowerment.",
        "target-demographic": "School children (ages 6–18)",
        "primary-concerns": "Quality of education, access to technology, skill development, exam pressure, and future career opportunities.",
        "cultural-beliefs": "Education as the key to personal and national growth, respect for teachers (Guru-Shishya tradition), and the importance of discipline and hard work.",
        "existing-values": "Love for learning, curiosity, patriotism, digital literacy, and moral responsibility.",
        "slogan": "Padhega Bharat, Badhega Bharat",
        "main-message": "Education is the most powerful tool for shaping the future. The government is committed to making learning enjoyable, skill-oriented, and future-ready for every child.",
        "tone": "Encouraging, motivational, and friendly.",
        "cultural-context": "India’s deep respect for education and teachers, focus on holistic development, and emerging digital transformation in schools.",
        "formality": "Semi-formal and engaging.",
        "speech-length": "600 words (short and impactful).",
        "speech-type": "Inspirational, policy-oriented.",
        "primary-objective": "Inspire children to value education and reassure them about reforms making learning more engaging and less stressful.",
        "secondary-objective": "Introduce new policies like NEP 2020, digital classrooms, and skill-based learning.",
        "age-range": "6–18 years",
        "education-level": "Primary to senior secondary school students.",
        "caste-community": "Inclusive of all backgrounds.",
        "religious-affiliation": "Secular, appealing to all communities.",
        "political-climate": "Pro-education reforms, increasing use of digital tools, reducing exam stress, and making learning more practical.",
        "recent-events": "Introduction of the National Education Policy (NEP) 2020, expansion of digital education, reduction of board exam pressure, and increased scholarships.",
        "geographic-location": "Warangal (delivered in a government or private school).",
        "key-messages": "Education should be fun, students should dream big, technology is an enabler, and every child has unique potential.",
        "data-upload": "References to NEP 2020, e-learning platforms, and government initiatives like PM eVidya.",
        "story-elements": "A story of a child who overcame struggles with digital learning tools, a reference to APJ Abdul Kalam’s journey, and the importance of curiosity.",
        "call-to-action": "Students should embrace learning, be curious, use technology wisely, and aim for excellence.",
        "cta-instructions": "Study with curiosity, explore new subjects, and be future-ready.",
        "speech-tone": "Inspiring, warm, and engaging.",
        "language-dialect": "Simple Hindi with a mix of English (for accessibility).",
        "rhetorical-devices": "Storytelling, rhetorical questions, metaphors (e.g., 'Education is the ladder to success'), and repetition for emphasis.",
        "policy-points": "National Education Policy 2020, digital learning initiatives, vocational training, stress-free exams, and scholarships for underprivileged students.",
        "retrieved_info": ""
    },
]

if __name__ == "__main__":
    # for test in test_cases:
    #     response = generate_response(test)
    #     print("Generated Response:", response)

    response = generate_response(test_cases[6])
    print("Generated Response:", response)